name: gsum-bert
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch=1.7.1
  - torchvision=0.8.2
  - torchaudio=0.7.2
  - cudatoolkit=11.0
  - pip:
    - multiprocess==0.70.9
    - pyrouge==0.1.3
    - pytorch-transformers==1.2.0
    - tensorboardX==1
